### ISSUE TITLE
Spanish translation.

### ISSUE THREAD

**Issue by vidimus** [blueadamantine/mom2-ultimacena#1]
Hello, @blueadamantine , I'm thinking about translating your scenario into Spanish. Would you mind if I do it? Plus, are you available to update the scenario in case I did it (and fix any bugs I found in the process)?

**Comment by blueadamantine** [comment]
Hi @vidimus , I'm totally ok about the translation. Yes, I am available to update the scenario and fix any bugs, that would help me too, as I'm still learning to use Valkyrie.

**Comment by vidimus** [comment]
@blueadamantine , great. I will contact you when the translation is ready.

**Comment by vidimus** [comment]
Hello, @blueadamantine 
I've sent you the info by discord.
Anyway here is the translation file:
[Localization.Spanish.txt](https://github.com/blueadamantine/mom2-ultimacena/files/5278751/Localization.Spanish.txt)

**Comment by blueadamantine** [comment]
Hi, @vidimus. I've added your translation to the file, though I have to tell you I made some minor changes that added extra text. I'm loading all the files to the repository.

**Comment by vidimus** [comment]
Hello, @blueadamantine 

Here's the update for the translation. 
[Localization.Spanish.txt](https://github.com/blueadamantine/mom2-ultimacena/files/5284859/Localization.Spanish.txt)


I'm still seeing the issues I've commented on discord (have you read the message?). 

Are you not going to add the score and comment option at the end of the scenario?

**Comment by vidimus** [comment]
Translation redone with the new text and other changes.

Here's the file (I've also sent it to you by discord).

[Localization.Spanish.txt](https://github.com/blueadamantine/mom2-ultimacena/files/5322308/Localization.Spanish.txt)

**Comment by blueadamantine** [comment]
> Are you not going to add the score and comment option at the end of the scenario?

I didn't know I could do it. I have to search in the guide to see how to.

**Comment by vidimus** [comment]
> > Are you not going to add the score and comment option at the end of the scenario?
> 
> I didn't know I could do it. I have to search in the guide to see how to.

Hello, @blueadamantine 

There's already a vote and a comment by a Spanish player, so that means it's already available, at least in one of the endings.

**Comment by vidimus** [comment]
[Localization.Spanish.txt](https://github.com/blueadamantine/mom2-ultimacena/files/5344426/Localization.Spanish.txt)

Updated with the new text lines.

**Comment by vidimus** [comment]
Hello, @blueadamantine 

It looks some text appears in Italian at the end of the scenario. I've checked and corrected (some of the values descriptions were cut, so the program used the original ones, in Italian). Now, finally, it should be all the text translated.

Could you please update the scenario with this new file?
[Localization.Spanish.txt](https://github.com/blueadamantine/mom2-ultimacena/files/5357973/Localization.Spanish.txt)

**Comment by blueadamantine** [comment]
> Hello, @blueadamantine
> 
> It looks some text appears in Italian at the end of the scenario. I've checked and corrected (some of the values descriptions were cut, so the program used the original ones, in Italian). Now, finally, it should be all the text translated.
> 
> Could you please update the scenario with this new file?
> [Localization.Spanish.txt](https://github.com/blueadamantine/mom2-ultimacena/files/5357973/Localization.Spanish.txt)

Done.

**Comment by vidimus** [comment]
Thanks, @blueadamantine

**Comment by blueadamantine** [comment]
Thank you, @vidimus :)
